version: '3.4'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - /opt/where-is-myHospital-mongodb/mongo-1/data:/data/db
    ports :
      - '27017:27017'
  rest-api-node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3500:3500'
    links:
      - mongodb
    volumes:
      - ./:/usr/src/app/
    restart: on-failure